export interface Producto {
  id: string
  nombre: string
  precio: number
  imagen: string
  categoria: string
  unidad: string
  supermercado: string
  supermercadoUrl: string
}

export const productos: Producto[] = [
  {
    id: "1",
    nombre: "Fideos Spaguetti Molitalia 450g",
    precio: 3.60,
    imagen: "/images/productos/fideos-spaguetti-molitalia-450g.webp",
    categoria: "Pastas",
    unidad: "450g",
    supermercado: "Tottus",
    supermercadoUrl: "https://www.tottus.com.pe",
  },
  {
    id: "2",
    nombre: "Leche Gloria Sixpack Lata 390g c/u",
    precio: 21.90,
    imagen: "/images/productos/leche-gloria-sixpack-lata-390g.webp",
    categoria: "Lácteos",
    unidad: "6 unid",
    supermercado: "Metro",
    supermercadoUrl: "https://www.metro.pe",
  },
  {
    id: "3",
    nombre: "Avena Quaker Tradicional 900g",
    precio: 10.90,
    imagen: "/images/productos/avena-quaker-tradicional-900g.webp",
    categoria: "Cereales",
    unidad: "900g",
    supermercado: "Wong",
    supermercadoUrl: "https://www.wong.pe",
  },
  {
    id: "4",
    nombre: "Azúcar Rubia BELL'S Bolsa 5Kg",
    precio: 20.30,
    imagen: "/images/productos/azucar-rubia-bells-5kg.webp",
    categoria: "Endulzantes",
    unidad: "5Kg",
    supermercado: "Vivanda",
    supermercadoUrl: "https://www.vivanda.com.pe",
  },
  {
    id: "5",
    nombre: "Papel Higiénico Suave Empaque 4 Rollos",
    precio: 7.90,
    imagen: "/images/productos/papel-higienico-suave-4-rollos.webp",
    categoria: "Higiene Personal",
    unidad: "4 unid",
    supermercado: "Metro",
    supermercadoUrl: "https://www.metro.pe",
  },
  {
    id: "6",
    nombre: "Arroz Superior Costeño Bolsa 5Kg",
    precio: 21.90,
    imagen: "/images/productos/arroz-superior-costeno-5kg.webp",
    categoria: "Granos",
    unidad: "5Kg",
    supermercado: "Plaza Vea",
    supermercadoUrl: "https://www.plazavea.com.pe",
  },
  {
    id: "7",
    nombre: "Huevos Pardos La Calera x30",
    precio: 21.50,
    imagen: "/images/productos/huevos-pardos-la-calera-x30.webp",
    categoria: "Proteínas",
    unidad: "30 unid",
    supermercado: "Metro",
    supermercadoUrl: "https://www.metro.pe",
  },
  {
    id: "8",
    nombre: "Agua Cielo sin Gas Botella 2.5L",
    precio: 2.5,
    imagen: "/images/productos/agua-cielo-sin-gas-2-5l.webp",
    categoria: "Bebidas",
    unidad: "2.5L",
    supermercado: "Plaza Vea",
    supermercadoUrl: "https://www.plazavea.com.pe",
  },
  {
    id: "9",
    nombre: "Pollo Fresco con Menudencia San Fernando x Kg",
    precio: 8.40,
    imagen: "/images/productos/pollo-fresco-menudencia-san-fernando-por-kg.webp",
    categoria: "Carnes",
    unidad: "por Kg",
    supermercado: "Wong",
    supermercadoUrl: "https://www.wong.pe",
  },
  {
    id: "10",
    nombre: "Sal de Mesa Marina Emsal Bolsa 1Kg",
    precio: 2.40,
    imagen: "/images/productos/sal-de-mesa-marina-emsal-1kg.webp",
    categoria: "Condimentos",
    unidad: "1Kg",
    supermercado: "Tottus",
    supermercadoUrl: "https://www.tottus.com.pe",
  },
  {
    id: "11",
    nombre: "Filete de Atún Florida en Aceite Vegetal x3",
    precio: 13.00,
    imagen: "/images/productos/filete-atun-florida-aceite-vegetal-x3.webp",
    categoria: "Conservas",
    unidad: "3 latas",
    supermercado: "Vivanda",
    supermercadoUrl: "https://www.vivanda.com.pe",
  },
  {
    id: "12",
    nombre: "Aceite Vegetal Primor Botella 900ml",
    precio: 8.90,
    imagen: "/images/productos/aceite-vegetal-primor-900ml.webp",
    categoria: "Aceites",
    unidad: "900ml",
    supermercado: "Tottus",
    supermercadoUrl: "https://www.tottus.com.pe",
  },
]
